### ISSUE TITLE
Abrechnungen: Thymeleaf auf Angular umstellen

### ISSUE THREAD

**Issue by Lobedan** [mosaic4cap/mosaic4cap-webapp#16]
Um den Abrechnungen mehr dynamik zu verleihen, soll von Thymeleaf Variablen auf Angular JS umgestellt werden.
Um ein weiteres Laden von Daten vom Backend zu unterbinden werden die Daten über die **Modeldefinition** an die HTML Seite weitergegeben und mit `th:attr=data-<<name>>=${<<name>>}"`an Angular weitergegeben.
Dadurch sind sie noch für Thymeleaf verfügbar und können trotzdem von Angular genutzt werden.

**Aktuelle Problemstellung:**
Daten können nur in JSON formatiert an Angular weitergegeben werden. Dadurch sind 2 Methoden in den Definitionen erforderlich. Evtl. kann als Feature eine automatische Konvertierung stattfinden.
Im Moment reicht es noch eine Methode für Rohdaten (<<name>>) und eine Methode für JSON Formatierte Daten (<<name>>AsJson) zu erstellen.

TODO:
- [x] Abrechnungen-Übersicht auf **Angular umstellen**
- [x] Klick auf Abrechnung macht Feld **Active**
- [x] --^-- --^-- --^-- --^-- **füllt Felder** auf der rechten Seite 
- [x] **Paging** für Teilabrechnungen
- [x] **"Autocommit"** beim ausfüllen der Felder
- [x] **entgültige Speicherung** der Abrechnung in extra SQL Tabelle

**Comment by Lobedan** [comment]
**Autocommit** und *_entgültige Speicherung_ wurden nicht implementiert.
Stattdessen wird `state == InvoiceType.Closed`gesetzt wenn alle Abrechunngen geschlossen sind.

**TODO:**
- [ ] Json Mapping mit gleichen Ids
